package crazy

object Raw {

  final case class Boo2020_10_05(
                                          salesRegion: String,
                                          region: String,
                                          market: String,
                                          country: String,
                                          regionalOrigin: String,
                                          strategicGroup: String,
                                          designParent: String,
                                          salesParent: String,
                                          salesGroup: String,
                                          salesBrand: String,
                                          salesNameplate: String,
                                          globalNameplate: String,
                                          platform: String,
                                          program: String,
                                          actualDate: String,
                                          GVWRating: String,
                                          globalIndustrySegment: String,
                                          globalIndustryRegion: String,
                                          productionType: String,
                                          carTruck: String,
                                          off_Type: String,
                                          globalSalesSegment: String,
                                          globalSalesSubSegment: String,
                                          globalSalesPriceClass: String,
                                          regionalSalesSegment: String,
                                          regionalSubSegment: String,
                                          regionalSalesPriceClass: String,
                                          architecture: String,
                                          mnemonicNamplateCountry: String,
                                          monthsInMarket: Int,
                                          vehicleLifeCycleinMonth: Int,
                                          year2010: Int,
                                          year2011: Int,
                                          year2012: Int,
                                          year2013: Int,
                                          year2014: Int,
                                          year2015: Int,
                                          year2016: Int,
                                          year2017: Int,
                                          year2018: Int,
                                          year2019: Int,
                                          year2020: Int,
                                          year2021: Int,
                                          year2022: Int,
                                          year2023: Int,
                                          year2024: Int,
                                          year2025: Int,
                                          year2026: Int,
                                          year2027: Int,
                                          year2028: Int,
                                          year2029: Int,
                                          year2030: Int,
                                          year2031: Int,
                                          year2032: Int
                                        )

}
